// Fallback demo jobs used only when live sources return nothing (offline/dev).
export const SEED_JOBS = [
  { source: "seed", sourceId: "seed_1", title: "Senior Full-Stack Engineer", company: "Vercel", location: "Remote (US)", remote: true, url: "https://vercel.com/careers", salary: "$170k–$220k", tags: ["react", "next.js"], description: "Build the Next.js platform. React, TypeScript, Node, serverless infrastructure on AWS. Ship product features used by millions of developers.", postedAt: new Date().toISOString() },
  { source: "seed", sourceId: "seed_2", title: "Senior Software Engineer, ML Platform", company: "Databricks", location: "Remote", remote: true, url: "https://databricks.com/careers", salary: "$180k–$240k", tags: ["python", "ml"], description: "Python, machine learning infrastructure, Kubernetes, Spark. Build the platform data teams love.", postedAt: new Date().toISOString() },
  { source: "seed", sourceId: "seed_3", title: "Staff Product Engineer", company: "Notion", location: "San Francisco / Remote", remote: true, url: "https://notion.so/careers", salary: null, tags: ["react", "typescript"], description: "TypeScript, React, product-minded engineering. Own features end to end at a fast-growing product company.", postedAt: new Date().toISOString() },
  { source: "seed", sourceId: "seed_4", title: "Backend Engineer, Payments", company: "Stripe", location: "Remote (US)", remote: true, url: "https://stripe.com/jobs", salary: "$160k–$230k", tags: ["api"], description: "Java, Go, distributed systems, PostgreSQL, AWS. Build the economic infrastructure of the internet.", postedAt: new Date().toISOString() },
  { source: "seed", sourceId: "seed_5", title: "Senior Consultant, Cloud Solutions", company: "Accenture Solutions", location: "Bangalore", remote: false, url: "https://accenture.com/careers", salary: null, tags: ["consulting"], description: "Client-facing consulting role delivering cloud migration projects. AWS, stakeholder management, vendor coordination.", postedAt: new Date().toISOString() },
  { source: "seed", sourceId: "seed_6", title: "Machine Learning Engineer, LLMs", company: "Anthropic", location: "San Francisco", remote: false, url: "https://anthropic.com/careers", salary: "$280k–$405k", tags: ["llm", "python"], description: "Python, PyTorch, LLM training and evaluation, NLP. Work on frontier AI safety and capability research.", postedAt: new Date().toISOString() },
];
